### ISSUE TITLE
issue while using this api

### ISSUE THREAD

**Issue by pradeepkusingh** [sndyuk/logback-more-appenders#10]
This API never sends traffic to fluentd 24224 port. I checked that we have UDP and TCP both opened.  Is there a way to debug issue ?

**Comment by sndyuk** [comment]
@pradeepkusingh If you've already checked there is any traffic to 24224 and you set up logback, you would have been able to see any error message on your console or a log file. Can you paste your `logback.xml` and log here?

**Comment by pradeepkusingh** [comment]
i can see my spring boot ( SPRING API logs) are going through to the Flaunted , not application logs. let me paste my config.

**Comment by sndyuk** [comment]
@pradeepkusingh I'm closing this issue since you seems to resolve it yourself. Reopen it if you still have problem.
