### ISSUE TITLE
Can't shut down cleanly because DaemonAppender can't be interrupted.

### ISSUE THREAD

**Issue by oker1** [sndyuk/logback-more-appenders#12]
My app can't shut down gracefully, because the thread started by DaemonAppender keeps running. I've checked the code, and seems like InterruptedException is caught and the method recurses into itself instead of exiting. This code is quite similar to Logback's builtin AsyncAppender, and that implementation breaks out of the loop when it catches an InterruptedException.

**Comment by sndyuk** [comment]
Thanks @oker1, It seems to be true... I don't know why I put the code https://github.com/sndyuk/logback-more-appenders/blob/master/src/main/java/ch/qos/logback/more/appenders/DaemonAppender.java#L64
In my current understanding, the InterruptedException is only occurred when `pool.shutdown();` is called. Are you planning to send pull request? (Or I'll fix it in a week).

**Comment by oker1** [comment]
I can do a PR tomorrow.

**Comment by oker1** [comment]
One more thing, I think the DaemonAppender accomplishes the exact same thing as AsyncAppender, so it seems redundant to me. It could be removed and stated in the README that you should wrap the appender in an AsyncAppender.

**Comment by sndyuk** [comment]
Yeah, I just checked AsyncAppender and it seems same. It would be able to remove bunch of code but I think it's good idea to replace to AsyncAppender 👍
