### ISSUE TITLE
Question: why MSG_SIZE_LIMIT Is needed?

### ISSUE THREAD

**Issue by fgaule** [sndyuk/logback-more-appenders#26]
Hi,
I'm wondering why MSG_SIZE_LIMIT Is used to shrink messages? I need to emit a huge event to fluentd (bigger than 65k) and it's getting only a part of it.

Regards

**Comment by sndyuk** [comment]
@fgaule It doesn't have a concrete reason. I think nobody won't have trouble if it's removed. so I would appreciate if you create p/r to remove it.

**Comment by fgaule** [comment]
@sndyuk Ready for code review #27

**Comment by sndyuk** [comment]
@fgaule Thank you. version 1.4.4 has been released.

**Comment by fgaule** [comment]
:clap: :clap:
