### ISSUE TITLE
Add additional fields at runtime

### ISSUE THREAD

**Issue by mahanhz** [sndyuk/logback-more-appenders#30]
Is it possible to support adding additional fields at runtime for ch.qos.logback.more.appenders.FluencyLogbackAppender?

At the moment one can specify additional fields up front inside the logback file, but say I wanted to add a customerId field (key value pair) to the log output, but customerId is only known at runtime.

I'm thinking of functionality along the lines of logstash MapEntriesAppendingMarker.

**Comment by sndyuk** [comment]
@mahanhz You may be able to use the logback(SLF4J)'s feature: MDC https://logback.qos.ch/manual/mdc.html

**Comment by mahanhz** [comment]
MDC is an option. 
It's just that it's a bit tricky to use given that you have to make sure you clear it to avoid retaining the MDC information that was previously added to the thread.
It's even trickier using it in async or reactive systems.

**Comment by sndyuk** [comment]
@mahanhz Please close the issue if you have no further question here #31

**Comment by zonybob** [comment]
Do you plan to tag a 1.5.1 release and push to maven central? Thanks again!

**Comment by sndyuk** [comment]
@zonybob Yes, 1.5.1 has been released. FYI: 1.5.2 also has been released just now!(It'll be synced in a few hours)

https://repo.maven.apache.org/maven2/com/sndyuk/logback-more-appenders/1.5.1/

**Comment by mahanhz** [comment]
Great news. Looking forward to using it.
