### ISSUE TITLE
Support of the version 2.0 of Fluency

### ISSUE THREAD

**Issue by Erouan50** [sndyuk/logback-more-appenders#35]
Version 2.0 of Fluency seems to be not compatible with the current version of the appender. Are you planning to support it?

**Comment by sndyuk** [comment]
@Erouan50 We can plan it but I'm not a Fluentd user recently... so if you or somebody raise the p/r, It would be helpful!

**Comment by pmaciolek** [comment]
An attempt to provide the support is here: https://github.com/sndyuk/logback-more-appenders/pull/36

**Comment by sndyuk** [comment]
@pmaciolek LGTM👍 Published 1.5.5 with the fix. It'll be synced Maven central in a few hours.
