### ISSUE TITLE
Bug toString of MapMarker class

### ISSUE THREAD

**Issue by hogmuzzle** [sndyuk/logback-more-appenders#41]
Apparently we have NPE here

@Override
    public String toString() {
        if (mapStr == null) {
            mapStr = mapStr.toString();
        }
        return getName() + '{' + mapStr + '}';
    }

**Comment by mahanhz** [comment]
I have submitted a PR to resolve this issue. 
toString() should be called on the map rather than mapStr.

See https://github.com/sndyuk/logback-more-appenders/pull/42

**Comment by sndyuk** [comment]
@mahanhz Thanks!
