### ISSUE TITLE
Output log contains both msg and message fields in FluencyLogbackAppender

### ISSUE THREAD

**Issue by sar009** [sndyuk/logback-more-appenders#45]
because of the following lines in FluentdAppenderBase we are getting both `msg` and `message` in the output. Shouldn't the `msg` be put if this is not an instance of ILoggingEvent.
https://github.com/sndyuk/logback-more-appenders/blob/master/src/main/java/ch/qos/logback/more/appenders/FluentdAppenderBase.java#L43

```java
    protected Map<String, Object> createData(E event) {
        Map<String, Object> data = new HashMap<String, Object>();
        data.put(DATA_MSG, encoder.encode(event));

        if (event instanceof ILoggingEvent) {
            ILoggingEvent loggingEvent = (ILoggingEvent) event;
            data.put(DATA_MESSAGE, loggingEvent.getFormattedMessage());
```

**Comment by ClintEsteMadera** [comment]
@sar009 there is a small typo in you IF condition: forgot a `!`?

**Comment by sndyuk** [comment]
@sar009 Sorry for the late reply. It sounds reasonable.
Also it looks `msg` should be removed and use `message` instead.
I'll fix it. Thanks!

**Comment by sndyuk** [comment]
It's been released as 1.8.0.

**Comment by ClintEsteMadera** [comment]
@sndyuk I need this change badly for today. Would you be so kind to upload 1.8.0 to Maven central or let me know how I can produce a jar to (temporarily) use it? Thanks a lot in advance for your help!

**Comment by ClintEsteMadera** [comment]
> @sndyuk I need this change badly for today. Would you be so kind to upload 1.8.0 to Maven central or let me know how I can produce a jar to (temporarily) use it? Thanks a lot in advance for your help!

never mind. I wasn't seeing this version in mvnrepository.com but it is indeed published and available. Thanks a lot!!
