### ISSUE TITLE
Exceptions should be handled or reported instead of swallowed

### ISSUE THREAD

**Issue by d10n** [sndyuk/logback-more-appenders#47]
In `protected void append(E event) {`:
https://github.com/sndyuk/logback-more-appenders/blob/2b10bee00e14f665b8ba48519e2ad63ed3c728bf/src/main/java/ch/qos/logback/more/appenders/FluencyLogbackAppender.java#L102-L104

**Comment by sndyuk** [comment]
@d10n Thanks! It's been released as 1.8.0. 
For the time being, the error is going to be reported. (but I'm not sure there is a better way than it, not to omit the log message)

https://github.com/sndyuk/logback-more-appenders/commit/6cc2ac9165cfc1b1ff4e416d7653225668ee38ee
