### ISSUE TITLE
feature request: flattenMapMarker behavior improvement

### ISSUE THREAD

**Issue by mlasevich** [sndyuk/logback-more-appenders#51]
it appears the flattenMapMarker option offers choice between two options - either ignore the marker id or mangle it - can we add a new option to actually use the marker name?

I.e. if i add marker with name "data" - use "data" as marker name instead of "marker.data"?

**Comment by sndyuk** [comment]
@mlasevich Sorry for the late reply. I think it's a good option. but I actually don't understand well so if you make p/r it will be helpful. Thanks!

**Comment by mlasevich** [comment]
Let me look at it. TBH, its been a while and I am trying to recall what was going on for this...

**Comment by mlasevich** [comment]
The PR is a bit larger, but short of it is that I made the prefix that is currently hardcoded be an option that can be set - including being set to a blank.

**Comment by sndyuk** [comment]
It's been released on 1.8.3. Thanks!

**Comment by mlasevich** [comment]
thanks
