### ISSUE TITLE
line data couldn't get

### ISSUE THREAD

**Issue by whbq** [sndyuk/logback-more-appenders#55]
<appender name="FLUENT_SYNC"
              class="ch.qos.logback.more.appenders.DataFluentAppender">

        
        <tag>debug</tag>
        

        
        <port>32429</port>
        
        <additionalField>
            <key>foo</key>
            <value>bar</value>
        </additionalField>
        <additionalField>
            <key>foo2</key>
            <value>bar2</value>
        </additionalField>
        
        <flattenMapMarker>false</flattenMapMarker>

        <encoder>
            <pattern><![CDATA[%date{HH:mm:ss.SSS} [%thread] %-5level %logger{15}#%line %message]]></pattern>
        </encoder>
    </appender>

**Comment by sndyuk** [comment]
@whbq What is "line data"? Could you give me more detail?
