### ISSUE TITLE
CloudWatch appender and AWS SDK v2

### ISSUE THREAD

**Issue by jklap** [sndyuk/logback-more-appenders#63]
Looks like the CloudWatch appender is currently using v1 of the AWS SDK.

Any plans to make another (guessing one in parallel to the current appender) to support v2?

**Comment by sndyuk** [comment]
@jklap I don't have the plan yet but it's better to support v2 as well.

**Comment by jklap** [comment]
Had a couple of hours this weekend-- take a look at the PR I just sent

**Comment by sndyuk** [comment]
https://github.com/sndyuk/logback-more-appenders/pull/64
