### ISSUE TITLE
MDC properties are not passed to DataFluentLogger

### ISSUE THREAD

**Issue by suyambuganesh** [sndyuk/logback-more-appenders#7]
MDC properties are not passed to DataFluentLogger as the MDC properties are loaded lazily while processing the data.

**Comment by suyambuganesh** [comment]
@sndyuk Thanks for having a look at the issue. Also it would be very nice to release the new version to central mvn repo.

**Comment by sndyuk** [comment]
@suyambuganesh 1.3.0 was released just now. Thanks :)
```
<dependency>
  <groupId>com.sndyuk</groupId>
  <artifactId>logback-more-appenders</artifactId>
  <version>1.3.0</version>
</dependency>
```
