### ISSUE TITLE
CloudWatch appenders duplicate logs

### ISSUE THREAD

**Issue by daniloarcidiacono** [sndyuk/logback-more-appenders#70]
Hello,
I've found a bug affecting `CloudWatchIntervalAppender`.
Consider the loop done by the `append()` method:

```java
long size = 0;
int putIndex = 0;
for (int i = 0, l = events.size(); i < l; i++) {
    InputLogEvent event = events.get(i);
    String message = event.getMessage();
    size += (message.length() * 4); // Approximately 4 times of the length >= bytes size of utf8
    if (size > 1048576 || i + 1 == l) {
        PutLogEventsRequest request;
        if (i + 1 == l) {
            request = new PutLogEventsRequest(logGroupName, streamName, events.subList(putIndex, i + 1));
        } else {
            request = new PutLogEventsRequest(logGroupName, streamName, events.subList(putIndex, i));
            i -= 1;
        }
        size = 0;
        putIndex = i;

        // .... redacted ...
    }
}
```

In general, `subList(fromIndex, toIndex)` returns a list view spanning from `fromIndex` **inclusive** to `toIndex` **exclusive**.

Consider the scenario when the loop has accumulated enough data but it has not gathered all the events, so `i + 1 < l`.
The control flow proceeds to the else branch, so `subList(putIndex, i)` is invoked and the event index `i`, say 10, is decreased, so it is set to 9.

After that, `putIndex` is set to the (updated) value of `i`, 9, which is incorrect. The next chunk will begin from the latest `putIndex` (9) which was already been sent as the last element of the previous chunk (`subList(putIndex, 10)`).

I fixed the problem simply by assigning `putIndex` before decrementing `i`:

```java
if (size > 1048576 || i + 1 == l) {
    PutLogEventsRequest request;
    if (i + 1 == l) {
        request = new PutLogEventsRequest(logGroupName, streamName, events.subList(putIndex, i + 1));
    } else {
        request = new PutLogEventsRequest(logGroupName, streamName, events.subList(putIndex, i));
        // Update putIndex before decreasing the event index
        putIndex = i;
        i -= 1;
    }
    size = 0;
    
    // ....redacted....
}
```

I didn't try `CloudWatchLogbackAppenderV2` but it seems to have the same issue.

Thanks

**Comment by sndyuk** [comment]
@daniloarcidiacono Thanks! It should be correct. Could you create the P/R?
